using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CambioModoCamara : MonoBehaviour
{
    public Camera camaraTerceraPersona; // Referencia a la c치mara de tercera persona.
    public Camera camaraPlanoGeneral; // Referencia a la c치mara de plano general.

    private bool modoPlanoGeneral = false;

    void Start()
    {
        // Inicialmente, activa la c치mara de tercera persona y desactiva la c치mara de plano general.
        camaraTerceraPersona.enabled = true;
        camaraPlanoGeneral.enabled = false;
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Z))
        {
            modoPlanoGeneral = !modoPlanoGeneral;
            CambiarModoCamara(modoPlanoGeneral);
        }
    }

    void CambiarModoCamara(bool planoGeneral)
    {
        if (planoGeneral)
        {
            // Modo Plano General
            camaraTerceraPersona.enabled = false;
            camaraPlanoGeneral.enabled = true;
        }
        else
        {
            // Modo Tercera Persona
            camaraTerceraPersona.enabled = true;
            camaraPlanoGeneral.enabled = false;
        }
    }
}
